title: Just the Docs Test Docs
description: Test for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

utl: https://zmijewskik.github.io/documentation-test

aux_links:
  Template Repository: https://github.com/zmijewskik/documentation-test
